### ISSUE TITLE
Move from unsigned long to enum?

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr-hands-input#17]
The IDL has a large number of hardcoded `unsigned longs`. Would it be clearer to move them to a `enum`

**Comment by Manishearth** [comment]
The problem with enums is that they're not extensible, further joints cannot be added without content being unable to use the new variant name on older devices without getting a type error .

Consts are often used for cases like this, e.g. see the Node interface.

**Comment by cabanier** [comment]
What would happen if you use a new joint type on old content? Would it not throw an error?

**Comment by Manishearth** [comment]
@cabanier no, in the current implementation it would return null in the getter. applications need to be able to handle this anyway because different devices/user agents may support different joints

> Not all devices support all joints, this indexing getter will return `null` when accessing a joint that is not supported by the current user agent or device. This will not change for a given input source. If a joint is supported but not currently being tracked, the getter will still produce the `XRJointSpace`, but it will return `null` when run through `getPose` (etc).

**Comment by cabanier** [comment]
> @cabanier no, in the current implementation it would return null in the getter. applications need to be able to handle this anyway because different devices/user agents may support different joints
> 
> > Not all devices support all joints, this indexing getter will return `null` when accessing a joint that is not supported by the current user agent or device. This will not change for a given input source. If a joint is supported but not currently being tracked, the getter will still produce the `XRJointSpace`, but it will return `null` when run through `getPose` (etc).

Numbers still feel very awkward and C++ like. I would much rather have a list of predefined string names.

**Comment by cabanier** [comment]
@Manishearth what are the numbers you currently implemented?

**Comment by Manishearth** [comment]
> Numbers still feel very awkward and C++ like. I would much rather have a list of predefined string names.

[Node uses this pattern as well](https://dom.spec.whatwg.org/#dom-node-element_node). 

I don't like putting us in a situation where we have to partially reimplement string matching (there are a bunch of spec gotchas there) so that we can have extensible enums.

> @Manishearth what are the numbers you currently implemented?

All of them. Microsoft's openxr extension supports all of these joints (and will never return a partial set, it's all-or-nothing and backends are required to emulate ones it can't track). I did not include the openxr palm joint in this API, nor any of the oculus-specific ones like thumb trapezium joints. I tried to start off conservative.

**Comment by cabanier** [comment]
> > Numbers still feel very awkward and C++ like. I would much rather have a list of predefined string names.
> 
> [`Node` uses this pattern as well](https://dom.spec.whatwg.org/#dom-node-element_node).
> 
> I don't like putting us in a situation where we have to partially reimplement string matching (there are a bunch of spec gotchas there) so that we can have extensible enums.

We don't need enums, regular DOMString would work.

> > @Manishearth what are the numbers you currently implemented?
> 
> All of them. Microsoft's openxr extension supports all of these joints (and will never return a partial set, it's all-or-nothing and backends are required to emulate ones it can't track). I did not include the openxr palm joint in this API, nor any of the oculus-specific ones like thumb trapezium joints. I tried to start off conservative.

Where is the list of these numbers? Are they Microsoft specific?

**Comment by Manishearth** [comment]
> We don't need enums, regular DOMString would work.

oh fair, this won't have the same situation as the issues we had with feature descriptor parsing since it's _only_ domstring

but I don't particularly view a string-based api as more webby than a const-based one.

> Where is the list of these numbers? Are they Microsoft specific?

I think you misunderstand the explainer, the precise numbers there don't matter and aren't copied from anywhere, I just neglected to fill them in in the explainer. My intent was for them to be increasing, starting at 0.

these are the values I decided to use:

https://github.com/servo/servo/blob/b0bf182316292b0d76f7c87e322370331ad0497f/components/script/dom/webidls/XRHand.webidl#L12-L40

**Comment by Manishearth** [comment]
I can copy those numbers into the explainer if you'd like. That was just an oversight on my part; the numbers don't matter much.

**Comment by cabanier** [comment]
> I can copy those numbers into the explainer if you'd like. That was just an oversight on my part; the numbers don't matter much.

Yes please :-)

**Comment by Manishearth** [comment]
Done: https://github.com/immersive-web/webxr-hands-input/commit/b5d963ed4970a3054b950e1b06bcfc03b56575ce

There's no logic to them aside from "increasing order" (which enables iteration), we could potentially lay them out in a grid fashion so that you can calculate a given joint as `finger * stride + joint` but that seems like overkill.
